name: "Deploy to AWS" # Name of action.

on: # when to run action named, Deploy.
  push:
    branches:
      - main # when commit happens to this branch.

jobs:
  deploy: # Name of Job/Task, can have any number of jobs/tasks.
    runs-on: ubuntu-latest # this is github's own machine, like our local machine.

    steps:
    - name: Checkout code # To clone the code. 
      uses: actions/checkout@v2 

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ssh -t -i keyfile ubuntu@ec2-13-48-5-59.eu-north-1.compute.amazonaws.com "source ~/deploy.sh"